//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterManagerProject.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PrintTagDbEntities : DbContext
    {
        public PrintTagDbEntities()
            : base("name=PrintTagDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<tBatch> tBatches { get; set; }
        public virtual DbSet<tDrug> tDrugs { get; set; }
        public virtual DbSet<tZHY> tZHies { get; set; }
        public virtual DbSet<tDept> tDepts { get; set; }
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tWarning> tWarnings { get; set; }
        public virtual DbSet<tOrderBak> tOrderBaks { get; set; }
        public virtual DbSet<tWarningBak> tWarningBaks { get; set; }
    
        public virtual int P_BakHistoryData(string use_date)
        {
            var use_dateParameter = use_date != null ?
                new ObjectParameter("use_date", use_date) :
                new ObjectParameter("use_date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_BakHistoryData", use_dateParameter);
        }
    
        public virtual int P_InsertIntotOrderSelecttZHY(string use_date)
        {
            var use_dateParameter = use_date != null ?
                new ObjectParameter("use_date", use_date) :
                new ObjectParameter("use_date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_InsertIntotOrderSelecttZHY", use_dateParameter);
        }
    
        public virtual int P_UpdatetOrderFromtZHY(string use_date)
        {
            var use_dateParameter = use_date != null ?
                new ObjectParameter("use_date", use_date) :
                new ObjectParameter("use_date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_UpdatetOrderFromtZHY", use_dateParameter);
        }
    }
}
