//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterManagerProject.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrintTagDbEntities : DbContext
    {
        public PrintTagDbEntities()
            : base("name=PrintTagDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<tBatch> tBatches { get; set; }
        public virtual DbSet<tDrug> tDrugs { get; set; }
        public virtual DbSet<tZHY> tZHies { get; set; }
        public virtual DbSet<tDept> tDepts { get; set; }
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tWarning> tWarnings { get; set; }
    }
}
