//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterManagerProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBatch
    {
        public int Id { get; set; }
        public string batch { get; set; }
        public string batch_name { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
    }
}
