//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterManagerProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDrug
    {
        public int Id { get; set; }
        public string drug_code { get; set; }
        public string drug_name { get; set; }
        public string drug_spec { get; set; }
        public string drug_units { get; set; }
        public string drug_use_spec { get; set; }
        public string drug_use_units { get; set; }
        public string drug_form { get; set; }
        public string input_code { get; set; }
    }
}
